services:
  proxy:
    build:
      context: .
      dockerfile: docker/proxy.Dockerfile
    container_name: skills-exchange-proxy
    ports:
      - "8080:80"
    depends_on:
      - app
      - frontend

  app:
    build: .
    container_name: skills-exchange-app
    ports:
      - "80"
    volumes:
      - .:/var/www/html
    command: >
      sh -c "mkdir -p /var/www/html/uploads/avatars /var/www/html/logs && chown -R www-data:www-data /var/www/html/uploads /var/www/html/logs && chmod -R 755 /var/www/html/uploads /var/www/html/logs && apache2-foreground"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_NAME: ${skills_exchange}
      DB_USER: ${skills_user}
      DB_PASS: ${skills_pass}

  frontend:
    build:
      context: ./web
      dockerfile: react/Dockerfile
      args:
        API_BACKEND_URL: http://app:80
        NEXT_PUBLIC_API_ORIGIN: http://localhost:8080
    container_name: bartery_frontend
    ports:
      - "3000:3000"
    depends_on:
      - app
    environment:
      NODE_ENV: production
      API_BACKEND_URL: http://app:80
      NEXT_PUBLIC_API_ORIGIN: http://localhost:8080


  mysql:
    image: mysql:8.0
    container_name: skills-exchange-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${rootpass}
      MYSQL_DATABASE: ${skills_exchange}
      MYSQL_USER: ${skills_user}
      MYSQL_PASSWORD: ${skills_pass}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb-buffer-pool-size=128M
      - --max-connections=20
      - --performance-schema=OFF
      - --table-open-cache=100
      - --thread-cache-size=30

volumes:
  mysql_data:
